In [192]:

import numpy as np
import pandas as pd
import math

veri_ayrilmamis= np.array(
               [["sunny","hot","high","weak","no"]\
               ,["sunny","hot","high","strong","no"]\
               ,["overcast","hot","high","weak","yes"]\
               ,["rainy","mild","high","weak","yes"]\
               ,["rainy","cool","normal","weak","yes"]\
               ,["rainy","cool","normal","strong","no"]\
               ,["overcast","cool","normal","strong","yes"]\
               ,["sunny","mild","high","weak","no"]\
               ,["sunny","cool","normal","weak","yes"]\
               ,["rainy","mild","normal","weak","yes"]\
               ,["sunny","mild","normal","strong","yes"]\
               ,["overcast","mild","high","strong","yes"]\
               ,["overcast","hot","normal","weak","yes"]\
               ,["rainy","mild","high","strong","no"]\
              ])

In [193]:
FEATURES={}
def func_sutun_kategorilestirme(future_alan_param):
    olan_listesi=[]
    yeni_a=[]
    tur_no=1
    dict_tur_no_tut={}
    for a_kategori in range(len(future_alan_param)):
        var_mi=future_alan_param[a_kategori:(a_kategori + 1)]
        if var_mi not in olan_listesi:
            FEATURES[str(var_mi[0][0])]=tur_no
            olan_listesi.append(var_mi)
            yeni_a.append(tur_no)
            dict_tur_no_tut[tur_no]=var_mi
            tur_no +=1
        else:
            yeni_a.append(list(dict_tur_no_tut.keys())[list(dict_tur_no_tut.values()).index(var_mi)] )
    return yeni_a
kategorilestirme=veri_ayrilmamis[:,(len(veri_ayrilmamis[0])-1):len(veri_ayrilmamis[0])]
#print("kategorilestirme",kategorilestirme)
train_y=func_sutun_kategorilestirme(kategorilestirme)
#print("train_y",train_y)

In [194]:
kategorikOznitelikler=[];
for featureColumn in range(len(veri_ayrilmamis[0])-1):
    kategorilestirmex1=veri_ayrilmamis[:,featureColumn:featureColumn+1]
    train_x=func_sutun_kategorilestirme(kategorilestirmex1)
    kategorikOznitelik=np.array(train_x);
    kategorikOznitelikler.append(kategorikOznitelik)
kategorikOznitelikler.append(np.array(train_y))
veri=np.array(kategorikOznitelikler).transpose()
print("veri \n", veri)
print("")
print("öznitelikler\n",FEATURES)

veri 
 [[1 1 1 1 1]
 [1 1 1 2 1]
 [2 1 1 1 2]
 [3 2 1 1 2]
 [3 3 2 1 2]
 [3 3 2 2 1]
 [2 3 2 2 2]
 [1 2 1 1 1]
 [1 3 2 1 2]
 [3 2 2 1 2]
 [1 2 2 2 2]
 [2 2 1 2 2]
 [2 1 2 1 2]
 [3 2 1 2 1]]

öznitelikler
 {'no': 1, 'yes': 2, 'sunny': 1, 'overcast': 2, 'rainy': 3, 'hot': 1, 'mild': 2, 'cool': 3, 'high': 1, 'normal': 2, 'weak': 1, 'strong': 2}


In [195]:


#SoruListesi=list(map(lambda x:FEATURES[x], ["rainy","cool","normal","strong"]))
SoruListesi=list(map(lambda x:FEATURES[x], ["rainy","cool","normal","strong"]))



In [196]:

detayli_mi=input("Detayli sonuc icin D'ye basin\nDirekt karari görmek icin K'ye basin")
Son_Liste=[]

Detayli sonuc icin D'ye basin
Direkt karari görmek icin K'ye basind


In [197]:

for k in range(len(veri[0])-1):
    feature_=veri[:,k:(k+1)]
    Decition=veri[:,(len(veri[0])-1):len(veri[0])]   #karar son sutunda

    def bir_oznitelikteki_tur_sayisi(feature_):
        a=feature_.tolist()
        liste1=[]
        for b in range(len(a)):
            count = 0
            for element in a:
                count += element.count(b)
            if count!=0:

                liste1.append(b)
        return liste1
    tur_listesi_Dec=bir_oznitelikteki_tur_sayisi(Decition)

    p_feat_T_=[]
    for a in range(len(tur_listesi_Dec)):
        p_feat_T=(len(Decition[Decition==tur_listesi_Dec[a]]))
        if p_feat_T==0:
            p_feat_T=1
        p_feat_T_.append(p_feat_T)
    if detayli_mi=='D' or detayli_mi=='d':
        print(" sınıfların toplam frekanslari",p_feat_T_) # Sınıflarin  frekanslari
    p_feat_T_Olasiliklar=[]
    for a1 in range(len(p_feat_T_)):
        p_feat_T_Olasiliklar_gecici1=p_feat_T_[a1]/sum(p_feat_T_)
        p_feat_T_Olasiliklar.append(p_feat_T_Olasiliklar_gecici1)
    if detayli_mi=='D' or detayli_mi=='d':
        print(" sınıfların olasiliklari :",p_feat_T_Olasiliklar) # Sınıflarin  olasiliklari   
    tur_listesi=bir_oznitelikteki_tur_sayisi(feature_)
    def func1(feature_,tur_listesi,Dec_,tur_listesi_Dec):
        s_sonuc=[]
        b=1
        feature_G=feature_.tolist()
        for a1 in range(len(tur_listesi)):
            dec_yes_no_sififlar_=0
            s_sonuc_=[]
            for b in range(len(tur_listesi_Dec)):
                dec_yes_no_sififlar__=0
                for a2 in range(len(feature_)):
                    if (feature_[a2]==tur_listesi[a1]) and (Dec_[a2]==tur_listesi_Dec[b]):
                        dec_yes_no_sififlar__+=1
                s_sonuc_.append(dec_yes_no_sififlar__)
            s_sonuc.append(s_sonuc_)  
        return s_sonuc
    def P_feat(feature_):
        a=feature_.tolist()
        olasiliklar=[]
        for b in range(len(a)):
            count = 0
            for element in a:
                count += element.count(b)
            if count!=0:
                olasiliklar.append(count/len(a))
        return olasiliklar
    P_ler=P_feat(feature_)
    YveN_sayilari=func1(feature_,tur_listesi,Decition,tur_listesi_Dec)
    if detayli_mi=='D' or detayli_mi=='d':
        print("-------------------------------")
        print("öznitelik toplam frekns sayilari",YveN_sayilari)
        print("-------------------------------")
    
    olasilik_tum_listesi=[]
    for tempsayi1 in range(len(YveN_sayilari)):
        olasilik_listesi=[]
        for tempsayi in range(len(YveN_sayilari[0])):
            temp11=YveN_sayilari[tempsayi1][tempsayi]
            temp12=p_feat_T_[tempsayi]
            pl=temp11/temp12
            if detayli_mi=='D' or detayli_mi=='d':
                print((tempsayi+1)," Sinifina ait olmasi koşulu altinda "\
                  ,"  X",(k+1),"\t","özniteliğinin ",(tempsayi1+1),". turu olma olasiligi: ",pl)
            olasilik_listesi.append(pl)
        olasilik_tum_listesi.append(olasilik_listesi)
    if detayli_mi=='D' or detayli_mi=='d':
        print("________________________________________________")
        print("X",(k+1),"\t","özniteliğinin olasilik_listesi:",olasilik_tum_listesi)
        print("________________________________________________")
    Son_Liste.append(olasilik_tum_listesi)


 sınıfların toplam frekanslari [5, 9]
 sınıfların olasiliklari : [0.35714285714285715, 0.6428571428571429]
-------------------------------
öznitelik toplam frekns sayilari [[3, 2], [0, 4], [2, 3]]
-------------------------------
1  Sinifina ait olmasi koşulu altinda    X 1 	 özniteliğinin  1 . turu olma olasiligi:  0.6
2  Sinifina ait olmasi koşulu altinda    X 1 	 özniteliğinin  1 . turu olma olasiligi:  0.2222222222222222
1  Sinifina ait olmasi koşulu altinda    X 1 	 özniteliğinin  2 . turu olma olasiligi:  0.0
2  Sinifina ait olmasi koşulu altinda    X 1 	 özniteliğinin  2 . turu olma olasiligi:  0.4444444444444444
1  Sinifina ait olmasi koşulu altinda    X 1 	 özniteliğinin  3 . turu olma olasiligi:  0.4
2  Sinifina ait olmasi koşulu altinda    X 1 	 özniteliğinin  3 . turu olma olasiligi:  0.3333333333333333
________________________________________________
X 1 	 özniteliğinin olasilik_listesi: [[0.6, 0.2222222222222222], [0.0, 0.4444444444444444], [0.4, 0.3333333333333333]]
_____

In [198]:

SoruListesi1=SoruListesi[:]
for kpnnt in range(len(SoruListesi1)):
    SoruListesi1[kpnnt]=(SoruListesi1[kpnnt]-1)
karar_olasilik=[]
for kpnnt_siniflar in range(len(p_feat_T_Olasiliklar)):
    p_incisinif=p_feat_T_Olasiliklar[kpnnt_siniflar]
    for kpnnt1 in range(len(SoruListesi1)):
        p_incisinif*=Son_Liste[kpnnt1][(SoruListesi1[kpnnt1])][kpnnt_siniflar]
    karar_olasilik.append(p_incisinif)
print("olasiliklar= ",karar_olasilik)
sonuc_=max(karar_olasilik)
sonuc=karar_olasilik.index(sonuc_)
print((sonuc+1),".  sinifa ait olma olasilik degeri= %",100*round(sonuc_/sum(karar_olasilik),2))

olasiliklar=  [0.0034285714285714297, 0.015873015873015872]
2 .  sinifa ait olma olasilik degeri= % 82.0
